name: Setup and test

on: [ push, pull_request ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  tests:
    name: Setup and run tests
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --no-suggest
      - name: Run tests
        run: |
          composer validate --strict
